In [5]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from numpy import array

In [11]:
# 텍스트 리뷰 자료 지정.
docs= ['너무 재미있어요', '최고에요', '참 잘 만든 영화에요', '추천하고 싶은 영화입니다',
'한번 더 보고싶네요', '글쎄요', '별로예요', '생각보다 지루하네요', '연기가 어색해요',
'재미없어요']

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스 지정.
classes= array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

# 토큰화
token= Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

x= token.texts_to_sequences(docs)
print('\n 리뷰 텍스트, 토큰화 결과: \n', x)

# 패딩, 서로 다른 길이의 데이터를 4로 통일.
padded_x= pad_sequences(x, 4)
print('\n패딩 결과: \n', padded_x)

# 임베딩에 입력될 단어의 수 지정.
word_size= len(token.word_index)+1

# 단어 임베딩을 포함해 딥러닝 모델을 만들고 결과를 출력.
model= Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation= 'sigmoid'))
model.summary()

model.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])
model.fit(padded_x, classes, epochs= 20)
print('\n Accuracy: %.4f' % (model.evaluate(padded_x, classes)[1]))

{'너무': 1, '재미있어요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화에요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}

 리뷰 텍스트, 토큰화 결과: 
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]

패딩 결과: 
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]
Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 4, 8)              168       
                                                                 
 flatten_2 (Flatten)         (None, 32)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                         